### PR TITLE
Bump runtime and remove dconf access

### PR DESCRIPTION
**Pull request by bilelmoussaoui**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by phw** [comment]
@bilelmoussaoui Thanks a lot for this. I only saw your changes after I had started fiddling around with this in #24, which is now merged. I fixed the gifski build errors by providing a new package with bundles dependencies for the latest gifski release.

**Comment by bilelmoussaoui** [comment]
@phw thanks for taking care of that :) Btw, you don't have to bundle cargo dependencies on your tarballs. You can just use flatpak-cargo-generator from https://github.com/flatpak/flatpak-builder-tools

**Comment by phw** [comment]
> You can just use flatpak-cargo-generator from https://github.com/flatpak/flatpak-builder-tools

That thing does not really run for me, the flatpak-cargo-generator.py does not seem in a working state right now. But also I'm not really a fan of this. As I understand it it will generate the JSON to have all crates as separate sources. But it's much easier for me to update the single package in https://github.com/phw/gifski-bundle/ and just bump the version and checksum then it is to generate some unwieldy JSON which I then have to fiddle into the Peek flatpak-builder JSON file.

**Comment by bilelmoussaoui** [comment]
It does work fine for me, I wrote a guide on how to use it here https://belmoussaoui.com/2020/02/08/how-to-flatpak-a-rust-application/. Anyway, whatever makes it easier for is what really matters

**Comment by phw** [comment]
@bilelmoussaoui I submitted a fix to https://github.com/flatpak/flatpak-builder-tools/pull/92 :)

**Pull request closed without merging**
