### PR TITLE
Use rust-stable extension

### PR DESCRIPTION
**Pull request by Barthalion**

### CODE REVIEW

**Comment by Barthalion** [comment]
Hm, looks like I did something wrong. Either way, just a general idea to use `rust-stable` extension when https://github.com/ImageOptim/gifski/issues/12 gets resolved.

**Comment by phw** [comment]
See also the discussion at https://github.com/flatpak/flatpak-builder/issues/15

I quickly tried `cargo vendor` locally on the source download. It fills the vendor resources and gives me this to add to the projects `.cargo/config`:

```
[source.crates-io]
replace-with = "vendored-sources"

[source."https://github.com/meh/rust-ffmpeg-sys"]
git = "https://github.com/meh/rust-ffmpeg-sys"
branch = "master"
replace-with = "vendored-sources"

[source."https://github.com/pornel/rust-ffmpeg.git"]
git = "https://github.com/pornel/rust-ffmpeg.git"
branch = "master"
replace-with = "vendored-sources"
```

As this file does not exist I create it. But building with `cargo build` then fails with:

    error: no source URL specified for `source.https://github.com/pornel/rust-ffmpeg.git`, need either `registry` or `local-registry` defined

**Comment by pornel** [comment]
I think support for vendoring of git dependencies has been added very recently, and may not be in a stable build yet.

Try compiling without video?

**Comment by pornel** [comment]
With OpenMP I've only heard of linking problems (it makes the executable dependent on libgcc and libgomp).

**Pull request closed without merging**
