### PR TITLE
Update for release 1.1.0

### PR DESCRIPTION
**Pull request by phw**
This updated the PKGBUILD to release 1.1.0. 

This also updated the dependencies. This reverts https://github.com/flathub/com.uploadedlobster.peek/commit/d15b4cc2818d46c32e100772e74685ba837ce66d for mainly two reasons:

- Using the archive for ImageMagick is a bad idea: As soon as they make a new release they remove older versions, e.g. `ImageMagick-6.9.9-3.tar.xz` is not available anymore, as they have released `ImageMagick-6.9.9-18.tar.xz` in the meantime.
- I follow stable releases from Arch (as this is what I use and is best tested), and I just can take the commit IDs from their PKGBUILDs
- Likewise using the commit ID for peek itself is easier for me, as I have this right away without downloading the generated Github ZIP.

### CODE REVIEW

**Comment by Barthalion** [comment]
Uh, somehow you weren't added to repository collaborators. Fixed this now, so in the future, feel free to push your changes directly or merge them on your own. (From the new stuff, you can now post `bot, build` in the commit to test your changes.)

bot, build

**Comment by Barthalion** [comment]
Looks like it didn't work due to having it also in the middle of sentence…

bot, build

**Comment by phw** [comment]
@Barthalion Thanks a lot. Next release is near so I will likely just upgrade it when this is ready

**Comment by phw** [comment]
> Uh, somehow you weren't added to repository collaborators. Fixed this now [...]

@Barthalion Does not seem to have worked, I still have no write access to the repository :(

**Comment by Barthalion** [comment]
:+1:

**Pull request merged**
